site_name: yeti.sh
site_url: https://yeti.sh
repo_url: https://github.com/anatoly-scherbakov/yeti.sh
repo_name: yeti.sh
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2023 Anatoly Scherbakov

markdown_extensions:
  - admonition
  - markdown_del_ins
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - blogging:
      dirs:
        - blog
      theme:
        name: card
      time_format: "%d %B %Y"
  - iolanta
  - awesome-pages
  - macros:
      on_error_fail: true


theme:
  name: material
  # custom_dir: templates
  logo: images/yeti.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes

extra_css:
  - assets/css/yeti-sh.css
#  - //cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - //code.jquery.com/jquery-3.6.0.min.js
#  - //cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js
