site_name: yeti.sh
repo_url: https://github.com/anatoly-scherbakov/yeti.sh
repo_name: yeti.sh
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2021 Anatoly Scherbakov

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

plugins:
  - search
  - octadocs
  - octadocs-table
  - octadocs-provenance
  - octadocs-github
  - macros:
      modules:
        - octadocs.macros


theme:
  name: material
  # custom_dir: templates
  logo: images/yeti.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes

extra_css:
  - stylesheets/flake8-codes.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
