# https://github.com/netlify/build-image/issues/221

[build]
publish = "site/"
command = """
pip install --upgrade pip setuptools wheel &&
pip install -q poetry &&
poetry install &&
poetry run mkdocs build
"""
