# https://github.com/netlify/build-image/issues/221

[build]
publish = "site/"
command = """
pip install --upgrade pip setuptools wheel &&
python -m pip install --no-use-pep517 pygraphviz==1.9 &&
pip install -q poetry &&
poetry install &&
poetry run mkdocs build
"""
