[tool.poetry]
name = "yetish"
version = "0.1.0"
description = "https://yeti.sh website"
authors = ["Anatoly Scherbakov <altaisoft@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8"
mkdocs-material = "^7.1.9"
octadocs = "^0.0.39"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
