[tool.poetry]
name = "yetish"
version = "0.1.1"
description = "https://yeti.sh website"
authors = ["Anatoly Scherbakov <altaisoft@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
mkdocs-blogging-plugin = "^1.4.0"
markdown-del-ins = "^1.0.0"
mkdocs-awesome-pages-plugin = "^2.9.2"
iolanta = "^2.1.42"
pyld = ">=2.0.4,<3.0.0"
setuptools = "<81"
urlpath = "^2.0.0"

[tool.poetry.group.dev.dependencies]
jeeves-yeti-pyproject = "^0.2.36"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
