[tool.poetry]
name = "yetish"
version = "0.1.1"
description = "https://yeti.sh website"
authors = ["Anatoly Scherbakov <altaisoft@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8"
mkdocs-material = "^8.1.3"
octadocs = "^0.2.21"
mkdocs-blogging-plugin = "^1.4.0"

[tool.poetry.dev-dependencies]
pipdeptree = "^2.2.0"
plumbum = "^1.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
