- $id: KGStore
  $type: rdfs:Class

- $id: sparql-support
  domain: KGStore
  label: SPARQL

- $id: native
  label: Native

- $id: ui
  domain: KGStore
  label: UI

- $id: python-client
  domain: KGStore
  label: Python Client

- $id: source
  label: Repo

- $id: source-stars
  label: ⭐
  ∘:
    - source
    - gh:stargazers_count

- $id: python-client-stars
  label: ⭐
  ∘:
    - python-client
    - gh:stargazers_count

- $id: source-license
  label: ⚖️
  ∘:
    - source
    - gh:license

- $id: python-client-license
  label: ⚖️
  ∘:
    - python-client
    - gh:license

- $id: sparql1.1
  label: 1.1
