- $id: KGStore
  $type: rdfs:Class

- $id: sparql-support
  domain: KGStore
  label: SPARQL

- $id: version
  rdfs:domain: SPARQLSupport
  rdfs:range: xsd:string

- $id: native
  label: Native

- $id: ui
  label: UI

- $id: python-client
  label: Python Client

- $id: license
  label: License

- $id: sparql1.1
  label: 1.1
