on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy to GitHub pages
    runs-on: ubuntu-22.04
    steps:
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
