on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy to GitHub pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install -q poetry
      - run: poetry install
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
