$included:
  - $id: KGStore
    $type: rdfs:Class
    label: KGMS

  - $id: native
    label: Native

  - $id: python-client
    domain: KGStore
    label: Python Client

  - $id: source
    label: Repo

  - $id: source-stars
    label: ⭐
    ∘:
      - source
      - github:stargazers_count

  - $id: python-client-stars
    label: ⭐
    ∘:
      - python-client
      - github:stargazers_count

  - $id: source-license
    label: ⚖️
    ∘:
      - source
      - github:license

  - $id: release
    range: github:Release
    label: Updated
    ∘:
      - source
      - github:hasLatestRelease

  - $id: python-client-updated
    label: Updated
    ∘:
      - python-client
      - github:hasLatestRelease

  - $id: python-client-license
    label: ⚖️
    ∘:
      - python-client
      - github:license

  - $id: sparql1.1
    =: "1.1"
    comment: "Latest version of the language with update capabilities."

  - $id: https://github.com/RDFLib/sparqlwrapper
    title: SPARQLWrapper
    comment: Usable to communicate with databases which have SPARQL as single available interface.
